"use strict";
// Help for the "?" button in the top right of every page (the slide-out panel).
// One topic per page, keyed like the sidebar (app.js TABS).  This is plain data,
// not HTML: the page's security policy forbids injecting markup, so app.js builds
// the panel from these blocks.  A block is
//   "text"                     a paragraph — **bold** and `code` are understood
//   ["h", "Heading"]           a sub-heading
//   ["ul", ["item", ...]]      a bullet list (items understand the same markup)
//   ["fields", [["Label", "what it does"], ...]]  a field list; each Label is the field's
//                              exact on-screen label (test: TestHelpCoversEveryField)
//   ["cli", "ddgw --x\nddgw --y"]  command-line equivalents, shown as code
// Editing this file IS editing the help system.  Keep a topic's CLI block in step
// with the page (every GUI function has a command).
const DDGW_HELP = {
  topology: {
    title: "Topology",
    body: [
      "The whole gateway on one drawing. Each gateway is an item under **Topology** in the sidebar (right-click it ▸ **Rename…** or **Delete**; named by its address, or by the **Name** you give it in the gateway form: right-click the circle → Edit gateway; the name is shared by every node in the cluster); **＋ New gateway…** adds another. The dot beside a gateway there is the gateway for the cluster as a whole, built from its nodes, so it does not change with the node you picked in the Node menu: green while any node serves it, amber while it is only served degraded, dashed grey when every node has it paused, red when no node serves it (hover for the count). The drawing itself is the gateway as the nodes that serve it see it: if the node you picked does not serve the gateway (another subnet, removed from it, paused there), the circle, servers and domains are those of a node that does, asked for you, and the circle\'s tooltip says which. If no node serves it, you see the node you picked. Right-click a server (a square), a domain (a trapezoid) or the gateway (the circle) → **Statistics…** for graphs over the last hour, day or week: a server's **latency and loss**; a domain's latency and failed probes on that server; the gateway's **answer time as clients see it, errors, availability and queries per second** (with how many came from the cache). The history is kept 7 days and survives a restart. A server's and a domain's graphs are this node's own; the gateway's add up **every reachable node** of the cluster (a note beside the time buttons says how many), because the nodes each answer only the clients that reach them. Every change is saved and applied the moment you make it — there is no Apply button.",
      ["h", "What you are looking at"],
      ["ul", [
        "The **circle** is the gateway: the shared address (VIP) clients send DNS to. Hover it to see which cluster nodes are serving it right now, which one is the gateway controller, and each node's slot.",
        "**Test virtual MACs…** (right-click the circle) checks that replies addressed to a gateway's virtual MAC reach this node. It asks the router (or another neighbour) a question from a throwaway virtual MAC and listens for the answer, and does the same from the real MAC as a control. **Delivered**: virtual MACs work here. **Not delivered**: the network drops frames sent to a virtual MAC (a VMware port group that is not promiscuous, a cloud with one MAC per interface), so the router may hold the gateway's MAC and still never get traffic through; the dialog then offers **Use real MAC addresses**, which sets the shared option of that name for every node. **Inconclusive**: nothing answered even the real MAC, so nothing was proved. The test runs once when a gateway starts, its result is in the circle's tooltip, and a \"not delivered\" turns a healthy gateway amber. It never changes a setting by itself.",
        "The **squares** are the DNS servers it forwards to. Each shows its state and how fast it answers.",
        "The **trapezoids** are the domains each server must answer for it to count as healthy. Green means the test query answered; red means it did not.",
        "The **parallelograms** to the left of the circle are the nodes of the cluster (just this node when it is alone), this node first and marked with a star (*): green is serving this gateway, amber is up but not serving it yet, or serving while its own DNS servers are partly down (degraded: the tooltip says why, the same view the circle gives for this node), dashed grey is paused, dashed red is not answering. A node whose CPU, memory or fullest disk goes **over 85%** turns solid yellow (degraded) and says which, until all are back at 85% or below (the tooltip shows the numbers). Hover one for its address, its Ethernet interfaces' IPv4 and IPv6 global (GUA) addresses, last-seen time, version and whether it has the primary's latest settings; right-click for **Make controller…** (the node takes the controller role for all groups; the one that held it steps down afterwards), **Pause node…** / **Resume node**, **Restart…** and **Shut down…** (the host of the node, after you confirm; you are warned when a gateway would lose its last serving member), each for any reachable node, this one or another, **Remove from this gateway…**, **Host statistics…** or **Open this node**. A node removed from the gateway is not drawn; right-click the gateway ▸ **Add node** to bring it back.",
        "The **pills** to the right are the gateway's anycast addresses. Both sides stand four to a column (three when four would put a line to a server through a box) and spread outward in new columns after that; drag an anycast pill to any slot to change the order.",
        "Hover any item for its **uptime**: how long it has been online since it last came back (or how long it has been down) and how many failures it has had, for example “Online for 1m 1s - 0 failures”. A gateway, an anycast address, a server or a domain counts as online while it is green or yellow. Anyname notes the changes itself, even with no browser open, but only in memory, so the counting, failures included, starts again when Anyname restarts. Paused and grey items show nothing. `ddgw --canvas` prints the same.",
      ]],
      ["h", "Several subnets"],
      "A node runs a gateway only if its interface has an address in the gateway's subnet (IPv4, and IPv6 when the node has a global IPv6 address). On a node that does not, the gateway shows grey (“not running here”) and starts by itself once the node is addressed there; the cluster members on that subnet serve it meanwhile.",
      ["h", "Anycast addresses"],
      "Right-click the circle → *Add anycast address…* adds an extra IPv4 or IPv6 address of **any subnet**; it appears as a pill to the right of the circle (right-click it to edit or delete, or press Delete). They are not checked against the interface and take no part in the election: every node running the gateway puts them on its loopback (`lo`) and answers DNS on them, using the same servers and domains. Announce them to your routers on the **Anycast** page (Configure), or with your own routing daemon. An address is removed from `lo`, so the route is withdrawn, while no DNS server answers or the gateway is paused or stopped. It is added with a 10-second lifetime that Anyname keeps renewing, so if Anyname crashes the kernel removes it within seconds. The drawing shows whether each is announced from this node. When this node manages BGP, a pill is green when every neighbor has an established BGP session, amber when some are not established and some are, and red when none is, when there is no neighbor of that family, or when BGP is disabled on this node (a neighbor that is disabled or still connecting counts as not established) (IPv4 addresses count IPv4 neighbors, IPv6 addresses IPv6 ones). The **same anycast address can be added to several gateways** (the usual anycast setup: every site announces one address). It is then held on `lo` while **any** of those gateways has a DNS server answering, it is answered from the first of them (lowest group number) that can, and a gateway that cannot answer shows \"kept up by …\" in the pill's tooltip. An anycast address cannot equal a gateway's shared address.",
      ["h", "Colours"],
      ["ul", [
        "**Green** — working. **Amber** — degraded (some servers down, or the gateway is still starting). **Red** — down: clients cannot be answered. **Grey** — not yet known. **Dashed** — paused. A **blue line** from the gateway to a server means spread is on and that server is within the band of the fastest one, so queries take turns across the blue ones (see the DNS page).",
        "A gateway that has just been resumed or started shows amber “starting” until its DNS servers answer; it only starts serving once they do, so clients never reach a node that cannot answer yet.",
      ]],
      ["h", "Editing: right-click"],
      ["ul", [
        "Right-click the **circle**: *Edit gateway…*, *Add DNS server…*, *Add anycast address…*, *Pause / Resume gateway* ▸ *This node* / *All nodes*, *Delete gateway*.",
        "The **mouse wheel** over the drawing zooms it (around the pointer); double-click the empty drawing to fit it to the window again. **Drag the empty background** to move around the drawing in any direction. **Drag** a server left or right, a domain up or down, or an anycast address up or down to move it to another place — a dashed outline shows where it lands, Escape cancels, and the new order is saved when you let go.",
        "In **Add DNS server**, fill in the IP address and the **Name** is filled in from its reverse DNS record; fill in a host name as the Name and the address is looked up. This happens when you leave the field, and only into a field that is empty or still holds an earlier lookup — change the name to anything you like and it is kept. A domain name too long for its trapezoid is cut with “…” (hover for the whole name).",
        "Right-click a **square**: *Edit server…* (its address and an optional **name**, shown on the square under the address), *Add domain…*, *Pause / Resume server* ▸ *This node* / *All nodes*, delete it.",
        "Right-click a **trapezoid**: *Edit domain…*, *Add domain…*, *Pause / Resume domain* ▸ *This node* / *All nodes*, delete. The Delete key also deletes the selected item.",
      ]],
      "**Fallback servers** are set in *Edit gateway…* (right-click the circle). They are used only while **no** server of the gateway is in service (every one is down or paused): the gateway then answers from them (amber, “answering from the fallback servers”), and it goes back to its own servers as soon as one of them answers again. Fallbacks are never probed (the domains of your servers may be internal names a public resolver does not know) and always count as up.",
      ["h", "Pause and resume"],
      "Right-click a gateway, a server, a domain or an anycast address and choose **Pause ▸ This node** or **Pause ▸ All nodes** (and **Resume** the same way). *This node* is kept in this node's own settings, so the other nodes carry on; *All nodes* is shared, so every node follows. A paused gateway releases its address and stops answering; a paused server gets no queries or probes; a paused domain is simply not asked; a paused anycast address is not announced (the gateway keeps serving). Each scope is paused and resumed on its own: an item paused on both stays paused until both are resumed. When all but one of a server's domains are paused the server turns amber (a single domain is all that is checked); when all of them are paused it turns red and counts as down, and gets no queries, until one is resumed. Paused items are grey and dashed, and the tooltip says where.",
      ["h", "Which nodes serve a gateway"],
      "Every node of the cluster serves every gateway unless it is removed from it (a node that joins starts out removed from all of them). Right-click a node (the parallelograms left of the circle) and choose **Remove from this gateway…**: that node gives up the gateway's address and stops answering DNS for it, and it is no longer drawn on this gateway on any node. The others carry on. To put it back, right-click the gateway and choose **Add node**, then the node by name (the item appears while a node is removed); it serves again once its DNS servers answer. It is a shared setting, kept with the gateway, so it can be changed from any node and survives restarts. It is not a pause: a pause is for maintenance and is kept on the node itself (or paused on all nodes), while removing a node is the gateway's permanent list of who serves it. Other gateways on the node are not affected, a node that joins the cluster later is left out of every gateway when it joins (add it with **Add node** where it should serve; a gateway you create afterwards is served by every node), and the last node serving a gateway cannot be removed (pause the gateway on all nodes instead).",
      ["h", "Clusters"],
      "The drawing (address, servers, domains) is shared by the whole cluster and can be edited from any node. Pausing a gateway is per node. To work on another member, pick it in the **Node** menu in the top right.",
      ["h", "Fields"],
      "Every field of the forms on this page. Right-click the circle → *Edit gateway…* / *New gateway…* for the first form.",
      ["h", "Gateway form"],
      ["fields", [
        ["Group number", "1–255. Names the gateway: nodes that use the same number are one gateway, which is how a node joins an existing one. Chosen for you (the lowest unused number) and fixed once the gateway exists."],
        ["Name (optional)", "A label shown in the sidebar and on the circle instead of the address. Shared by every node in the cluster. Empty means the address is shown."],
        ["Shared IPv4 address / prefix", "The address clients send DNS to (the VIP), with its prefix length, for example `10.0.0.1/24`. A node serves the gateway only if its interface has an address in that subnet. Shared by the cluster."],
        ["Shared IPv6 address / prefix (optional)", "The same for IPv6, for example `2001:db8::1/64`. Leave empty for an IPv4-only gateway."],
        ["More IPv4 addresses (same subnet, optional)", "Further shared addresses inside the VIP's subnet, separated by commas, without a prefix length (`10.0.0.2, 10.0.0.3`). They move with the gateway together with the VIP and answer DNS (UDP, TCP, DoT and DoH) the same way; the VIP stays the one the nodes use to find each other. Up to 32. Shared by the cluster."],
        ["More IPv6 addresses (same subnet, optional)", "The same for IPv6 (`2001:db8::2`). Shared by the cluster."],
        ["Network interface", "The network card this node puts the VIP on (default `eth0`). It belongs to this node only: other cluster nodes keep their own."],
        ["Tell the DNS servers which network the client is on (ECS)", "**off** or **on**. On, the servers are told the client's network, so a server that understands it (Google 8.8.8.8, say) answers for the client's location instead of this node's. The prefix lengths (/24 and /56 by default) are in Configure ▸ DNS proxy ▸ Client network (ECS)."],
        ["Fallback DNS servers (optional)", "Servers, separated by commas, in the same forms as the upstream servers (`1.1.1.1`, `tls://…`, `https://…`). Asked only while every server of this gateway is down or paused, and dropped as soon as one answers again. They are never probed."],
        ["Load balancing", "**follow Settings** uses the load-balancing values of Configure ▸ DNS proxy (the hint shows what they are now); **own values** uses the six values below for this gateway only. The six fields below take effect only with *own values*."],
        ["Spread queries over servers of similar speed", "**on** or **off**. On, the servers within the spread band of the fastest one take turns; off, the fastest healthy server gets every query. See the DNS page."],
        ["Spread band (% of fastest)", "1–1000, default 20. A server whose latency is within this percent of the fastest one's is in the rotation; slower ones are fallbacks."],
        ["Down at (% of tests failing)", "1–100, default 100 (down only when every test fails; 50 = half). A server is down once this share of its probe queries fail (and has failed the number of rounds below)."],
        ["Failures before down", "Whole number from 1, default 2. Failed probe rounds in a row before a server is marked down."],
        ["Max servers tried", "Whole number from 1, default 3. How many servers a client query is tried on, one after another, before it gets SERVFAIL."],
        ["Latency smoothing (0–1]", "Above 0 and up to 1, default 0.3. How fast the smoothed latency (EWMA) follows new measurements: 1 uses only the latest, a small number averages over many."],
      ]],
      ["h", "DNS server form (Add DNS server / Edit server)"],
      ["fields", [
        ["IP address or host name", "The server to forward to. Add `:port` for a port other than 53; write `tls://host` for DNS over TLS (port 853) or `https://host/path` for DNS over HTTPS (port 443). Typing an address looks up its name, and typing a host name here fills the address."],
        ["Name (optional)", "A label of up to 40 characters, shown under the address on the square. Filled in from the reverse DNS record when you enter an address; yours is kept once you change it."],
        ["Domain to ask it about", "Only when adding: the first domain this server is probed with. A server counts as healthy only while it answers its domains; add more afterwards."],
        ["Record type", "The record type asked for in that probe: A, AAAA, NS, MX, TXT, SOA or CNAME. Default A."],
      ]],
      ["h", "Domain form (Add domain / Edit domain)"],
      ["fields", [
        ["Domain to ask about", "A name this server must answer for the probe to pass, such as `google.com`. The same name and type can be listed once per server."],
        ["Record type", "A, AAAA, NS, MX, TXT, SOA or CNAME. Default A."],
      ]],
      ["h", "Anycast form (Add anycast address / Edit anycast address)"],
      ["fields", [
        ["Anycast address", "A plain IPv4 or IPv6 address of any subnet, without a prefix. It cannot be loopback, link-local, multicast or an address another gateway already uses. Every node running the gateway holds it on `lo` while a DNS server answers."],
      ]],
      ["h", "Statistics windows"],
      ["fields", [
        ["Failed probes", "A server's window: the share of its own test queries that failed in each period. Only probes count here, because the probes decide whether the server is up. Not shown for a period with no probes."],
        ["Failed queries", "A server's window: the share of client queries sent to it that failed (no answer in time, SERVFAIL or REFUSED). A server that passes its probes can still show some, for names it cannot resolve; they do not take it out of service."],
        ["Time range", "The buttons **Last hour**, **Last day** and **Last week** choose how much history the graphs show. They are per window; the history kept is 7 days."],
      ]],
      ["cli", "ddgw --canvas\nddgw --canvas-pause gateway|server|domain|anycast ... --scope node|all\nddgw --canvas-add gateway --vip 10.0.0.1/24 --interface eth0\nddgw --canvas-add server --group 1 --server 10.0.0.53 --name example.com\nddgw --canvas-set gateway --group 1 --vip 10.0.0.2/24\nddgw --canvas-set gateway --group 1 --label \"Office DNS\"   (--label - clears it)\nddgw --canvas-add anycast --group 1 --address 203.0.113.53\nddgw --canvas-del anycast --group 1 --address 203.0.113.53\nddgw --canvas-set gateway --group 1 --anycast 203.0.113.53,2001:db8:53::1   (replaces the whole list; - clears it)\nddgw --canvas-del server --group 1 --server 10.0.0.53\nddgw --canvas-set gateway --group 1 --spread-band 200   (this gateway's own load balancing; also --spread on|off, --down-percent, --fail-threshold, --max-attempts, --latency-alpha; --lb settings follows Settings again)\nddgw --canvas-move server --group 1 --server 10.0.0.53 --to 1   (also domain … --name DOMAIN, anycast … --address ADDR: the drag in the drawing)\nddgw --dns-lookup 10.0.0.53   (its reverse name; or give a name for its address — what the Add DNS server form fills in)\nddgw --server-stats 10.0.0.53   (how that server has answered: latency and loss; --stats-range 1h|1d|7d)\nddgw --server-stats 10.0.0.53 --name example.com --type A   (one domain on that server)\nddgw --gateway-stats 1   (the gateway of group 1: answer time, errors, availability, queries, cache)\nddgw --canvas-del node --group 1 --node lsitedns02   (remove a node from a gateway; --node is its address or host name; --canvas-add node puts it back)\nddgw --test-vmac [--group 1]   (do virtual MACs reach this node? changes nothing)\nddgw --canvas-set gateway --group 1 --real-macs on   (run without virtual MACs on every node; off goes back)\nddgw --canvas-pause gateway --group 1\nddgw --canvas-resume server --group 1 --server 10.0.0.53\nddgw --canvas-set server --group 1 --server 10.0.0.53 --label dns-a   (a name shown instead of the address; - clears)"],
    ],
  },
  gateways: {
    title: "Gateways",
    body: [
      "For each gateway group and address family, the nodes taking part and what each is doing. Refreshes every 2 seconds; ★ marks this node. Every gateway is listed, whichever node the Node menu has picked: one that node does not run is shown as a node that serves it sees it (nothing starred).",
      ["h", "Reading the table"],
      ["ul", [
        "**Node name** is the node's name (its host name, from the cluster) and **Node IP** the address the node uses in the gateway protocol; the name is – for a node the cluster does not know, or until that node runs a version that reports its addresses.",
        "**AGC** (active gateway controller) is the one node that owns the shared address and answers ARP/neighbour requests for it. **AFN** nodes forward traffic and share the load. A node that is listening or has not been heard from yet has no role.",
        "**Pri** is the election priority (higher wins). **Slot** is the node's virtual-MAC slot: slot 1 always belongs to the controller, other nodes take 2 and up. **Weight** is its share of client traffic.",
        "**State** is where the node is in the protocol: *active* for the controller, *forward* for a forwarder, *standby* for a node that has no slot yet (a node still in an election shows as standby too), *expired* for one not heard from within the hold time. The node you are on shows its own exact state (listen, speak…); **preempt** marks nodes that take the role back as soon as they outrank the current controller. **Age** is how long since its last hello.",
        "**DNS** says whether the node answers DNS on the address (“answering”) or only has it enabled.",
      ]],
      "If nothing is listed on a network that should have peers, check the group id, the HMAC key and the interface on both nodes, and that multicast (or the unicast neighbour list in Settings) can pass between them.",
      ["cli", "ddgw --show-gateways\nddgw --show-neighbors"],
    ],
  },
  nodes: {
    title: "Cluster",
    body: [
      "Every node that shares settings with this one: its **name** and **IP** addresses (IPv4, IPv6 global and unique local; hover the name for the node's cluster address), its **role** (primary or replica), whether it is **reachable**, its **epoch**, the version it is **running** and the version of the **source** it holds (they differ while an update is under way), and when it was last seen. The node you are logged in to is marked ★. Adding, removing and promoting nodes is on the Cluster page; this card only watches.",
      ["cli", "ddgw --cluster-status"],
    ],
  },
  dns: {
    title: "DNS",
    body: [
      "The state of each gateway's pool of upstream DNS servers, fastest first. Refreshes every 2 seconds. Every gateway is listed, whichever node the Node menu has picked: one that node does not run is shown as a node that serves it sees it; the query totals at the top are the picked node's own.",
      ["h", "How servers are chosen"],
      ["ul", [
        "Every server is probed on a schedule with the test queries. A server is **up** while fewer than the **down at** share of its test queries fail (100% by default, so a server is down only when every test fails; set 50 to drop it when one of two or two of four fail); with some failing but under that share it stays in use and shows **amber** (degraded). It goes **down** after the configured number of failed rounds in a row, and comes back with the first round that passes.",
        "A client query goes to the fastest healthy server first (smoothed latency; with **spread** on, to the servers within the band of it in turns), and falls over to the next on failure, up to the configured number of attempts. If none is healthy the client gets a SERVFAIL.",
        "**Server name** is the name given to the server on the Topology page (right-click the server ▸ Edit server…; – when it has none) and **Server IP** the server as configured. **Rank** is the order used, **EWMA** the smoothed latency, **Last** the latest, **OK/Fail** the probe counts, **Served** the queries it has answered, and **Last error** why the last probe failed.",
      ]],
      "**Fallback servers** (marked *fallback* in the list, Configure ▸ DNS proxy ▸ Servers ▸ Fallback servers, or *Edit gateway…* on the Topology page) take no queries while any normal server is up; they get a rank only while every normal server is down, and the header says so.",
      ["h", "Spreading queries"],
      "With **Spread queries over servers of similar speed** on (the default) the servers whose latency is within **Spread band (% of fastest)** (20 by default) of the fastest one's take turns, round-robin, so the load is shared between them; a server slower than that stays a fallback until it is within the band. When the server whose turn it is fails or answers SERVFAIL or REFUSED, the next one is tried as before. The band is a percentage, so very small latencies (0.2 ms against 0.3 ms) are not in one; the **Served** column shows how the queries were really shared. Turn it off and the fastest healthy server gets every query, the others being only fallbacks. Configure ▸ DNS proxy ▸ Load Balancing sets this for every gateway; a gateway can have its own (Topology ▸ right-click the gateway ▸ Edit gateway ▸ Load balancing ▸ own values), and the DNS page shows the band each pool really runs with.",
      ["h", "Client Rate Limiting"],
      "**Allowed clients** (Configure ▸ DNS proxy ▸ Clients ▸ Client Rate Limiting) lists the networks that may use the proxy, one per line (10.0.0.0/8, 192.168.1.5, 2001:db8::/32); empty means everyone. Anyone else is answered REFUSED, and that includes dynamic DNS updates. **Queries per second** limits each client (one IPv4 address, or one IPv6 /64) to a rate, with a **burst** it may send at once (0 = twice the rate, at least 10); a client over it gets what **Over the limit** says: *drop* (nothing is sent: the safest choice, since a forged source address cannot be used to bounce answers at someone), *truncate* (a short UDP answer with the truncated bit, which makes a real resolver retry over TCP) or *refused*. TCP, DoT and DoH clients are always answered REFUSED. **Never limited** lists networks exempt from the rate (not from the allowed list). This node itself is always allowed and never limited. Both checks come before the cache. The pool's header shows the limit and how many queries were turned away or refused; the log says so at most once a minute. The counts are per node, so a client that reaches several nodes can send the limit to each. Applies to every gateway, including one with its own DNS servers and domains: its own `dns` block does not keep a separate copy.",
      ["h", "The answer cache"],
      "Each pool answers a repeated query from memory for as long as the records' TTLs allow, so the servers are asked once per name and TTL instead of once per client. The header of each pool shows the share of queries answered from the cache (hits, out of the queries that could be cached) and how many answers are kept; hover it for the limit, the queries that are never cached and the answers pushed out because it was full. NOERROR answers (also “no data”) and NXDOMAIN are kept, the latter only with the zone's SOA, whose minimum says how long. An answer is kept for its shortest TTL, at most the **Cache: most seconds** setting, and clients see the TTL counting down. SERVFAIL, REFUSED, truncated answers, zone transfers, signed queries and queries with EDNS options other than a cookie are never cached. With client subnet (ECS) on, each client network gets its own entries. Adding, pausing, resuming or removing a server keeps the cache; changing the cache settings (size, most seconds, client subnet) or switching it off and on empties it, which is also the way to clear it. A node that has just started asks another cluster node for its most recently used answers (up to 20,000, with the age they have there) in the background, so it does not start cold; if no node answers it starts empty. The cache never serves an answer past its TTL, so with every server down a name that has expired gets SERVFAIL. Turn it off, or change its size, in Configure ▸ DNS proxy.",
      "Servers and their test domains are edited on the Topology page.",
      ["cli", "ddgw --show-dns   (includes the answer cache line: hits, misses, entries)"],
    ],
  },
  config: {
    title: "Configure",
    body: [
      "Every setting of this node, as a form. **Changes save and apply as you make them** — when you leave a field, pick an option or tick a box. If the daemon refuses a value, a red “Not saved” message says why and nothing is changed until you correct it.",
      ["h", "Pages (General, Gateway groups, DNS proxy, Web GUI, Cluster; every change saves from whichever page you are on)"],
      ["ul", [
        "**General** — log level.",
        "**Gateway groups** — one card per gateway (gateways are added and deleted on the Topology page, not here): group id, interface, VIPs, priority, weight, preemption, load-balance method, timers, key, and unicast neighbours. Fields tagged **shared** follow the cluster; the rest belong to this node only.",
        "**DNS proxy** — six tabs, each with its own help page (open Help while on the tab): **Servers**, **Health & balancing**, **Listeners**, **Resolution**, **Cache & ECS** and **Clients**. A gateway drawn on the Topology page has its own servers and domains instead of the defaults here.",
        "**Web GUI** — listen address, login group, PAM service, session timeout and lockout. Changing the listen address restarts the GUI and ends every session, so you are asked to confirm first.",
        "**Cluster** — the address the other nodes use to reach this one, the peer listen address and sync interval. Joining, promotion and membership are on the Cluster page.",
      ]],
      ["h", "In a cluster"],
      "A change to a shared setting made on a replica is sent to the primary, checked there and replicated to everyone within the sync interval. Use the **Node** menu (top right) to edit another member's own settings.",
      ["h", "Fields"],
      "Every field of the General, Gateway groups, Web GUI and Cluster pages. The fields of the DNS proxy page are in the help of its six tabs, one page per tab. A field tagged **shared** follows the cluster (a change goes to the primary and is replicated); the others are this node's own. Defaults are those of a new installation.",
      ["h", "General"],
      ["fields", [
        ["Log level", "`debug`, `info` (default), `warning` or `error`. The least important lines the daemon writes to the journal and the Log page."],
        ["Update every node automatically when a newer release is staged (one node at a time)", "Auto-update. On (the default), each node builds and installs a staged release by itself, one node at a time, and rolls back if the new version does not stay up. Ticking it asks you to confirm. Applies to the whole cluster."],
      ]],
      ["h", "Gateway groups (one card per gateway)"],
      ["fields", [
        ["Name", "Optional label shown instead of the address. Shared."],
        ["Group ID", "1–255. Nodes with the same ID are one gateway; the ID also keys the election. Shared."],
        ["Interface", "The network card this node uses for the gateway (default `eth0`). This node only."],
        ["IPv4 VIP/prefix", "The shared IPv4 address and prefix, for example `10.0.0.1/24`. Empty turns IPv4 off for the gateway. Shared."],
        ["IPv6 VIP/prefix", "The shared IPv6 address and prefix. Empty turns IPv6 off. Shared."],
        ["More IPv4 addresses", "Further shared addresses in the VIP's subnet, one per line, without a prefix length. They fail over with the VIP. Shared."],
        ["More IPv6 addresses", "The same for IPv6. Shared."],
        ["Priority", "0–255, default 100. The election: the node with the highest priority becomes the active gateway controller (ties go to the higher address). This node only."],
        ["LB method", "How clients are spread over the forwarders: `roundrobin` (default; each new request goes to the next forwarder), `weighted` (in proportion to each node's weight), `hostpinned` (a client always gets the same forwarder) or `failover` (one forwarder takes everything, the rest stand by). Shared."],
        ["Weight", "0–255, default 100. This node's share of traffic under the `weighted` method; ignored by the others. This node only."],
        ["Hello interval (ms)", "How often a node announces itself, default 333. Shared."],
        ["Hold time (ms)", "How long a neighbour may stay silent before it is considered gone, default 999. Keep it at least three times the hello interval. Shared."],
        ["Max forwarders", "1–255, default 128. The most nodes that take part as forwarders (AFN). Shared."],
        ["HMAC shared key", "The secret that signs the gateway protocol messages (default `dgw`). Every node of a gateway must use the same key, and a node with another key is ignored. Shared."],
        ["Preemption", "Ticked: a node with a higher priority takes the active role back from the current controller as soon as it is up. Unticked: it waits until the controller fails. This node only."],
        ["Use real MAC addresses (no virtual MACs)", "On is the default for a gateway you add (gateways that already existed keep their setting). Off is the older way: each forwarder has a virtual MAC and the controller covers a dead node's MAC. On: no virtual MACs at all. Every node holds the VIP on its loopback, the controller answers ARP and IPv6 neighbor requests with the **real** MAC of the node it picks (it learns the others' MACs from their frames and asks for the ones it has not heard), and nothing is taken over when a node dies: the controller announces the VIP at its own MAC with an unsolicited ARP/neighbor advertisement, which only the neighbors that honor one will follow; the rest keep sending to the dead node until their ARP entry ages out. Needed where virtual MACs cannot work: a VMware port group with promiscuous mode off, a cloud that allows one MAC per interface. Shared by the cluster; changing it restarts the gateway on each node. The vMAC column of the Gateways page then shows real MAC addresses (the controller knows them all, a forwarder only its own)."],
        ["Neighbors (unicast mode)", "One IP address per line: list **every** node of the gateway, this one too (each node skips its own address). With none (the default) the nodes find each other by multicast; use the list when multicast cannot pass between them, such as in a cloud network. Shared: it replicates to every node."],
      ]],
      ["h", "Web GUI"],
      ["fields", [
        ["Listen address", "`host:port` the GUI listens on, default `:53853`. Changing it restarts the GUI and logs everyone out, so you are asked to confirm."],
        ["Login group", "The operating-system group whose members may sign in (default `ddgw`)."],
        ["PAM service", "The `/etc/pam.d` service that checks passwords (default `ddgw`)."],
        ["Session idle timeout (min)", "From 1, default 30. A browser is signed out after this many idle minutes."],
        ["Failed logins before lockout", "1–1000, default 3. Wrong attempts, within the window below, that lock out that address, and that address together with that user name. A user name alone is never locked out, so nobody can lock an administrator out by failing logins for that name."],
        ["…within this many minutes", "From 1, default 1. The window in which the failed logins are counted."],
        ["Lockout lasts (minutes)", "From 1, default 15. How long the lockout lasts."],
        ["Minimum password length", "1–128, default 8 (0 or empty is the default). The fewest characters a password set on the Users page, or with `--user-add` and `--user-password`, may have. Existing passwords are not checked. Changing a user's password, deleting the user or letting the account expire signs that user out of every open session."],
        ["Username", "On the sign-in page: an operating-system user who is a member of the login group."],
        ["Password", "On the sign-in page: that user's password, checked through PAM. After too many wrong attempts the sign-in page is locked for a while."],
      ]],
      ["h", "Certificate (Web GUI tab)"],
      "The certificate this GUI is served with. Until you install one, Anyname makes its own self-signed certificate, which browsers warn about.",
      ["h", "Installing your own certificate"],
      ["ul", [
        "Paste or choose a certificate (a single file or the full chain, PEM) and its private key and install. It is checked — chain order, key match, validity, server-auth use and names — and served from the next connection, with no restart and no logout.",
        "No certificate yet? Create a **certificate request** (CSR), send it to your certificate authority and upload what comes back; leave the key box empty.",
        "**Revert** goes back to the previous certificate; **Regenerate** makes a fresh self-signed one.",
      ]],
      "In a cluster the certificate installed on the primary is copied to every member, and reverting it on the primary reverts them all. A certificate named in the configuration file overrides anything installed here. The page warns when the certificate expires within 30 days.",
      ["h", "Fields"],
      ["fields", [
        ["Certificate", "The certificate in PEM form, your own first and then any intermediate ones. Paste it or choose a file under it (**Certificate file**: `.pem`, `.crt`, `.cer` or `.txt`)."],
        ["Private key", "Its private key in PEM form, pasted or from a **Key file** (`.pem`, `.key` or `.txt`). Leave it empty when the certificate answers a request created here, because the key is already on this server."],
        ["Main name", "For a request: the common name, the main host name the certificate is for, for example `gw.example.com`."],
        ["Other names (one per line)", "For a request: further host names the certificate should cover."],
        ["IP addresses (one per line, optional)", "For a request: IP addresses the certificate should cover, so it can be used when you open the GUI by address."],
        ["Pending CSR", "The request that was created, read only. Copy it and send it to your certificate authority."],
      ]],
      ["h", "Cluster"],
      ["fields", [
        ["Binding address", "`host:port` the cluster port listens on, which the other nodes connect to. Default `:53854` (all addresses); give an address, such as `10.0.0.5:53854`, to bind to one."],
        ["Advertised address", "`host:port` the other members use to reach this node. Empty means this host's name with the listen port."],
        ["Sync interval (s)", "1–3600, default 5. How often replicas pull state and members are polled."],
      ]],
      ["cli", "ddgw --show-config\nddgw --configure       (interactive wizard)\nddgw --config-import FILE\nddgw --tls-status\nddgw --tls-install --cert-file F --key-file F\nddgw --tls-csr --cn NAME [--san NAME_OR_IP,...]\nddgw --tls-revert\nddgw --tls-regenerate"],
    ],
  },
  config_dns0: {
    title: "DNS proxy: Servers",
    body: [
      "Where queries go when nothing else decides. These are the default upstream servers for gateways that have none of their own (a gateway drawn on the Topology page has its own servers and domains instead). A server written `tls://host` is spoken to over TLS (DoT, port 853) and one written `https://host/dns-query` over HTTPS (DoH, port 443); the certificate must match the host unless **Accept any certificate from tls:// and https:// servers** is on, which is encrypted but not authenticated, so use it only when you must (`tls_insecure` in the `dns` block). Every field here is saved with the page, like the other tabs.",
      ["h", "Fields"],
      ["fields", [
        ["Servers", "The default upstream servers for gateways that have none of their own, one per line: `10.0.0.53`, `10.0.1.53:5353`, `[2001:db8::53]:53`, `tls://host` or `https://host/dns-query`. Shared."],
        ["Fallback servers", "Same forms. Asked only while no server above is in service, never probed, and always counted as up. Shared."],
        ["Probe queries", "The names every server is asked to prove it works, one per line: `example.com` or `example.com AAAA` (type A when none is given). Shared."],
        ["Accept any certificate from tls:// and https:// servers (insecure)", "Off by default. On, the certificate of a TLS or HTTPS upstream server is not checked: the traffic is encrypted but the server is not authenticated. Shared."],
      ]],
    ],
  },
  config_dns1: {
    title: "DNS proxy: Health & balancing",
    body: [
      "How the proxy decides which server gets a query and when a server counts as down. Every server is probed on a schedule with the probe queries (Servers tab); a client query goes to the fastest healthy server first and falls over to the next on failure. The DNS page shows the result live.",
      ["h", "Fields"],
      ["fields", [
        ["Spread queries over servers of similar speed (round-robin)", "On by default. The servers within the spread band of the fastest take turns; off sends everything to the fastest. Shared."],
        ["Spread band (% of fastest)", "1–1000, default 20. How much slower than the fastest server a server may be and still take turns. Shared."],
        ["Down at (% of tests failing)", "1–100, default 100. The share of probe queries that may fail before a server counts as down. Shared."],
        ["Failures before down", "From 1, default 2. Failed rounds in a row before a server is down. Shared."],
        ["Max servers tried", "From 1, default 3. Servers a client query is tried on before SERVFAIL. Shared."],
        ["Latency smoothing (0–1]", "Above 0 up to 1, default 0.3. How quickly the smoothed latency follows new samples. Shared."],
        ["Probe interval (ms)", "From 1, default 5000. How often each server is probed. Shared."],
        ["Probe timeout (ms)", "From 1, default 1000. How long a probe waits before it counts as failed. Shared."],
        ["Forward timeout (ms)", "From 1, default 1500. How long a client query waits on one server before the next is tried. Shared."],
      ]],
    ],
  },
  config_dns2: {
    title: "DNS proxy: Listeners",
    body: [
      "How clients reach the proxy: the ports for plain DNS, DNS over TLS and DNS over HTTPS. DoT and DoH are served to clients on the gateway address with the GUI certificate (Configure ▸ Web GUI). A dynamic update (RFC 2136, `nsupdate`) sent to the gateway is forwarded, unchanged, to the primary server named in the zone's SOA record when **Forward dynamic DNS updates** is on; the log shows each one and Statistics counts them as type UPDATE. The primary decides whether to accept it (TSIG key, access list) and sees this node's address as the source.",
      ["h", "Fields"],
      ["fields", [
        ["DNS port (UDP and TCP)", "1–65535, default 53. The port the gateway answers plain DNS on. Shared."],
        ["DNS over TLS port", "0–65535, default 0 (off); usually 853. Serves DoT with the GUI certificate (Configure ▸ Web GUI). Shared."],
        ["DNS over HTTPS port", "0–65535, default 0 (off); usually 443. Serves DoH at `/dns-query`. It cannot equal the other two ports. Shared."],
        ["Forward dynamic DNS updates to the zone's primary server", "On by default. Updates (`nsupdate`) are passed to the primary named in the zone's SOA; off answers them REFUSED. Shared."],
      ]],
    ],
  },
  config_dns3: {
    title: "DNS proxy: Resolution",
    body: [
      "What a particular client gets for a name. **Policy-Based Resolution** sends a query to servers of its own, answers it itself, or asks for another name, depending on who asks and what is asked; the **Sort list** orders the addresses in an answer for each client network. The policy table is shown a page at a time with a filter box above it.",
      ["h", "Fields"],
      ["fields", [
        ["Policy-Based Resolution enabled", "On by default. Off keeps the rows but every query goes to the gateway's servers as usual. Shared."],
        ["Log policy matches", "On by default. Writes a log line for each query a policy row applied to (`dns: policy row 3: 10.1.1.1 asked www.example.com A: answered null`), at most 100 a second; the rest are counted in one line. Shared."],
        ["Policy rows", "Sends a query to servers of its own, and perhaps for another name, depending on who asks and what is asked. One row per line of the table, with four columns: **Source client**, **Source name**, **Destination servers** and **Destination name**. The rows are read from the top and the first row that matches both the client and the name is used; a query that no row matches goes to the gateway's servers. **Source client** is `*` (every client), an address (`10.1.1.1`), a network (`10.10.10.0/24`) or several of them separated by commas. **Source name** is `*` (every name), a name (`reddit.com`, exactly that name) or `*.name` (`*.reddit.com`: `reddit.com` itself and every name below it). **Destination servers** are written like the servers above (`10.2.2.2`, `10.2.2.2:5353`, `tls://dns.example.com`, `https://dns.example.com/dns-query`), separated by commas; they are tried in the order given, and one that failed its last query is tried after the others. Instead of servers the cell can hold one word, and then the row answers by itself, without asking any server (and with no Destination name): `null` (A `0.0.0.0` and AAAA `::`, \"no data\" for every other type), `nxdomain` (the name does not exist), `nodata` (the name exists, with no records of that type), `refused`, or `pool` (the gateway's own servers answer, as if no row matched: put it above a broader row as an exception, for one client or one name). To answer with an address of your own, leave the servers blank and write the answer in **Destination name**: just the address (`10.5.5.5`, or `10.5.5.5, 2001:db8::5`) makes the name that address, and records give more control: `A 10.5.5.5, 10.5.5.6`, `AAAA 2001:db8::5`, `TXT \"some text\"`, several kinds separated by `;` (`A 10.5.5.5; AAAA 2001:db8::5`), `TTL 300` (seconds clients may keep the answer, default 60, anywhere in the cell), or `CNAME host.example.com` (the name is another name: the gateway looks the target up for the client and answers with the CNAME and what it found; a CNAME cannot be combined with other records). A query for a type the row has no records of gets \"no data\"; ANY gets everything. Records and servers are not combined in one row (the same text in the servers cell works too). The table holds up to 10000 rows, shown a page at a time (25 to 500 rows per page) with a **Filter rows** box above the table that keeps only the rows with that text in any cell; rows keep their numbers, which are the numbers in the policy log lines; rows are found by name, so a long table does not slow queries down. **Destination name** is the name the servers are asked for instead of the one the client asked. Blank (or `*`) asks for the client's own name. A row with a Destination name and no servers (or the word `pool`) asks the gateway's own servers for that name. A name (`zdnet.com`) asks for that name. `*.name` (`*.hardocp.com`, only on a row whose source name is a `*.name` too) keeps the part in front: `www.reddit.com` is asked as `www.hardocp.com`, and `reddit.com` as `hardocp.com`. The client's answer is turned back into an answer to the name it asked: the question and every record named like the name that was asked (or below a `*.name` destination) carry the client's name, the other records are as the servers sent them. This applies only to a row that has a Destination name; a row without one passes the servers' answer through untouched, DNSSEC signatures included. With a Destination name, a signed (DNSSEC) answer is not valid for the client's name, and a record of a type that may hold names that cannot be moved safely is answered with SERVFAIL. A source name can also have `*` and `?` inside its labels: `*` stands for any characters within one label (never a dot) and `?` for exactly one character. `*host?.sub?.xyzzy.com` matches `myhost1.sub2.xyzzy.com` but not `host.sub2.xyzzy.com`; `*host*.sub*.xyzzy.com` matches `host1.sub1.xyzzy.com` and `myhost.sub.xyzzy.com`, `ad-*.example.com` matches `ad-12.example.com` but not `x.ad-12.example.com`. A `*.` at the very front still means any labels in front, or none (`*.sub*.xyzzy.com` matches `sub9.xyzzy.com` and `a.b.sub9.xyzzy.com`). Such a pattern cannot be a Destination name, and a Destination name of the `*.name` kind needs a plain `*.name` source. A blank client or source name means `*`; a row with neither servers nor a Destination name is not saved (its servers cell is outlined until it has one). Every cell is edited in place. Drag a row by the dots at its left to change its order within the page (the first row that matches wins), or right-click ▸ **Move up** / **Move down** / **Move to top** / **Move to bottom**. Right-click a row for **Edit**, **Copy**, **Paste** (the copied row, or rows copied from a spreadsheet as tab-separated text in the column order above, go in below the row), **Add** (a new row below; the filter is cleared) and **Delete**; right-click below the rows to add one at the end. A row's servers are not probed, so they are never marked down, and when none of them answers the client gets SERVFAIL: the query does not fall back to the gateway's servers. Answers are cached for each row's servers and destination apart, so a client sent to one set never gets an answer cached for another. The sort list and the client limits apply as before. Shared."],
        ["Sort list enabled", "On by default. Off keeps the list but answers are left in the order the servers gave. Shared."],
        ["Sort list", "Orders the A and AAAA records of an answer for each client network, one entry per line: `client-network: preferred-network, preferred-network` (for example `10.1.0.0/16: 10.1.0.0/16, 10.0.0.0/8`). The first entry whose client network contains the asking client is used; `any` as the client network matches every client. Addresses inside the client's own network always come first, then those in the first preferred network, then those in the second, and so on; addresses in none of them keep their order after those. An entry that is just a network (`10.20.0.0/16`) is for every client: all such entries together give the order, and the one the asking client is in comes first. A network may be a single address. Only A and AAAA records are reordered, and only in a plain answer (an answer with other record types, or an error, is left as it came). The cached answer is not changed, each client gets its own order. Empty (the default) leaves the order the servers gave. Shared."],
        ["Sort list loops", "Not a field. A server of the gateway that sends queries to the gateway (its forwarder points at the gateway or at an anycast address) would make every such query go round until it times out, and the server would show as down. A query is never sent back to the server it came from, and the log names that server once a minute."],
      ]],
    ],
  },
  config_dns4: {
    title: "DNS proxy: Cache & ECS",
    body: [
      "What is reused between clients. Repeated queries are answered from memory for as long as the records' TTLs allow, so the servers are asked once per name and TTL instead of once per client. The client's network can be passed to the servers (ECS), which also decides how the cache is keyed; the DNS page shows the cache's hits, misses and size.",
      ["h", "Fields"],
      ["fields", [
        ["Pass the client's network to the servers", "On by default. Sends the client's network to the upstream servers (ECS). A gateway can override it in its own form. Shared."],
        ["IPv4 prefix bits", "1–32, default 24. How much of a client's IPv4 address is passed on. Shared."],
        ["IPv6 prefix bits", "1–128, default 56. How much of a client's IPv6 address is passed on. Shared."],
        ["Answer repeated queries from a cache", "On by default. Repeated queries are answered from memory for as long as the records' TTLs allow. Shared."],
        ["Most answers kept", "100–1,000,000, default 10000. When full, the least recently used answers go first. Shared."],
        ["Cache TTL (s)", "1–604800, default 3600. A cap on how long any answer is kept, whatever the TTL in its records. Shared."],
      ]],
    ],
  },
  config_dns5: {
    title: "DNS proxy: Clients",
    body: [
      "Who may use the proxy and how much. **Allowed clients** limits which networks may send queries; the rate limit applies per client, which is one IPv4 address or one IPv6 /64.",
      ["h", "Fields"],
      ["fields", [
        ["Allowed clients", "Networks that may use the proxy, one per line (`10.0.0.0/8`, `192.168.1.5`, `2001:db8::/32`). Empty (the default) allows everyone; anyone else is answered REFUSED. Shared."],
        ["Queries per second", "0 (the default) means no limit. A client is one IPv4 address or one IPv6 /64. Shared."],
        ["Burst (queries at once)", "How many queries a client may send at once. 0 means twice the rate, at least 10. Shared."],
        ["Over the limit", "`drop` (default; send nothing), `truncate` (a short UDP answer that makes the client retry over TCP) or `refused`. TCP, DoT and DoH clients are always answered REFUSED. Shared."],
        ["Never limited", "Networks exempt from the rate limit (not from the allowed list), one per line. Shared."],
      ]],
    ],
  },
  history: {
    title: "History",
    body: [
      "Every change to the configuration is recorded — from the GUI, the CLI, a cluster sync or a file edit — with who made it and a plain-words summary of what changed. Secrets are hidden in summaries. The newest 200 versions are kept.",
      ["ul", [
        "Click a version to select it (it is highlighted); the buttons in the list's header act on that one. **Diff vs previous** and **Diff vs live** compare it with its predecessor or with what is running now; **View** shows it in full.",
        "Tick two versions and choose **Compare ticked** to see exactly what differs between them.",
        "**Restore** applies an old version immediately. The current configuration is saved as a new version first, so you can always come back.",
        "**Download** saves the selected version as a file; **Upload** checks and applies a configuration file. **Snapshot now** records the current state as a version.",
      ]],
      ["h", "Fields"],
      ["fields", [
        ["Compare version", "The tick box on each version. Tick two and choose **Compare ticked** to see what differs between them."],
        ["Configuration file", "What **Upload** asks for: a configuration `.json` file, such as one saved with **Download**. It is checked first and applied only if valid."],
      ]],
      ["cli", "ddgw --versions\nddgw --version-show ID\nddgw --version-diff A[..B]\nddgw --version-snapshot [--note TEXT]   (a note can only be given here)\nddgw --version-restore ID\nddgw --version-export [ID]\nddgw --config-import FILE"],
    ],
  },
  cluster: {
    title: "Cluster",
    body: [
      "Clustering keeps the settings of several Anyname nodes in step and lets you update them together. It is separate from the gateway election, which works the same with or without it. Every node is the primary of a cluster of one until it joins another.",
      ["h", "Adding a node"],
      "On any member choose **Create join code**; on the new node paste it under **Join**. The code works once and for an hour. The new node's shared settings are replaced by the cluster's; its interface, priority and weight stay its own.",
      ["h", "Roles and membership"],
      ["ul", [
        "One node is the **primary**; the others are **replicas**. Shared settings are checked on the primary and copied out within the sync interval.",
        "If the primary is gone for good, choose **Promote** on the replica you want. Nothing promotes itself, so a network split can never create two primaries.",
        "Right-click a member (not this node) and choose **Remove**: it drops the member (it resets itself to a cluster of one when it next hears from the cluster); it can be allowed back with **Unremove**. **Leave cluster** does it from the node itself.",
        "**Sync now** pulls the latest state immediately.",
      ]],
      ["h", "Epoch"],
      "The epoch is a counter that says which node is the primary. It starts at 1 and goes up by one each time you **Promote** a node, and only then: restarts, joins, syncs, updates and members going offline never change it. Every member follows the primary with the highest epoch, so an old primary that comes back still claiming a lower epoch is ignored and falls in line as a replica. If two different nodes ever claim the same epoch (two admins promoting on either side of a network split), the nodes refuse the conflict instead of picking one. An epoch of 1 everywhere means nothing has been promoted yet.",
      ["h", "The Members table"],
      ["ul", [
        "**Reachable**: whether this node could ask that member for its status just now; when it says no, the reason is shown.",
        "**Epoch**: that member's view of the epoch (see above). They should all agree.",
        "**Running** and **Source**: the version the member is running, and the newest uploaded source version it holds.",
        "**Last seen**: when the member last answered.",
      ]],
      ["h", "Working on another member"],
      "Every page follows the **Node** menu in the top right, this one included. Pick a member and Leave, Promote, Create join code or Sync act on it.",
      ["h", "Security"],
      "Nodes pin each other's certificates and sign every request with the cluster secret. The cluster port (53854 by default) is separate from the GUI port and must be reachable between the nodes.",
      ["h", "Fields"],
      ["fields", [
        ["Node", "The menu at the top right of every page. It picks which member the page shows and acts on: this node (the default) or any other member of the cluster."],
        ["Join code", "On the new node: paste the code made by **Create join code** on a member. It is single-use, valid for an hour, and not shown again; the member shows it read only for you to copy."],
      ]],
      ["cli", "ddgw --cluster-status\nddgw --cluster-token\nddgw --cluster-join CODE\nddgw --cluster-promote\nddgw --cluster-remove ADDR / --cluster-unremove ADDR\nddgw --cluster-leave\nddgw --cluster-sync"],
    ],
  },
  updates: {
    title: "Upgrade",
    body: [
      "Update Anyname in place. Upload a release archive (`ddgw_vN.tgz` or `.zip`) to any node: it is checked and kept as the **source**, and the other members pull it from there. Auto-update is on by default, so each node installs a newly staged release by itself; turn it off in Configure ▸ General ▸ Upgrade to update nodes by hand. Each node builds the daemon itself, so it needs a Go toolchain, gcc and the PAM headers (the installer sets these up).",
      ["h", "Updating"],
      ["ul", [
        "**Update this node now** (top right of the Nodes card) installs the source here. In a cluster, tick one or more members first and the button becomes **Update N selected**: those members update one at a time.",
        "While auto-update is on, the button and the tick boxes are disabled; turn it off to update by hand.",
        "**Auto-update** (Configure ▸ General ▸ Upgrade) (on by default) makes every member update itself whenever a newer source exists. Withdrawing a queued update (`--update-cancel`) is command line only.",
        "Members update **one at a time**. A node only takes itself down when another member has been serving every gateway it serves for at least 15 seconds, so the gateway is always answered by someone and clients have moved back after the previous node's restart; otherwise it waits and the table says why. “Update now” on a node that is not safe to take down asks you to confirm before forcing it.",
        "A new version that does not come up is rolled back automatically.",
      ]],
      "The table (refreshed every 2 seconds) shows each member's version, source, whether it is queued or updating, and failures. The history lists every update event (the newest 500 are kept), newest first, 25 to a page: use **‹ Newer** and **Older ›** to move through them. Use the **Node** menu in the top right to work on another member.",
      ["h", "Fields"],
      ["fields", [
        ["Release archive", "Select a `ddgw_vN.tgz` (or `.zip`) release archive. It is checked and staged on this node; the other members pull it from here."],
        ["Select (tick box on each member row)", "Ticks a member for **Update N selected**. Disabled while auto-update is on (Configure ▸ General)."],
      ]],
      ["cli", "ddgw --update-status   (the 50 newest history events)\nddgw --update-history  (all of them)\nddgw --update-upload FILE\nddgw --update-apply\nddgw --update-push all|ADDR,...\nddgw --update-cancel all|ADDR,...\nddgw --update-auto on|off"],
    ],
  },
  anycaststatus: {
    title: "Anycast (monitor)",
    body: [
      "What BGP is doing on this node right now. The page refreshes every few seconds. The settings are under **Configure → Anycast**; switching BGP or a neighbor off and on is under **Operate → Anycast**.",
      ["h", "The page"],
      ["ul", [
        "**Status**: the local AS, whether FRR is installed and `bgpd` answers, and what the last apply did.",
        "**Neighbors**: the BGP session state read from FRR (*Established* is a working session; a neighbor you disabled shows *disabled*; right-click a neighbor and choose **Disable** or **Enable**), the **BFD** state (*up* means the router answers fast failure detection, *down* means it does not), how long the session has been up and how many prefixes were sent to it.",
        "**Anycast addresses**: every anycast address of every gateway and whether this node announces it. An address is *withdrawn* while no DNS server answers, the gateway is paused or not running here, or the address could not be added to `lo`; the reason is shown.",
      ]],
      ["cli", "ddgw --bgp"],
    ],
  },
  anycast: {
    title: "Anycast",
    body: [
      "Announce the gateways' **anycast addresses** to your routers with BGP. Anyname drives FRR on this node: it writes `/etc/frr/frr.conf` (BGP only), turns `bgpd` and `bfdd` on and reloads FRR. FRR must be installed on the node. What BGP is doing is shown under **Monitor → Anycast**; switching BGP or a neighbor off and on is under **Operate → Anycast**.",
      ["h", "What it does"],
      ["ul", [
        "**Per node.** The AS, router ID and neighbors are not shared with the cluster — each node usually peers with its own upstream router. The anycast addresses themselves are shared (right-click a gateway on the Topology page → *Add anycast address…*).",
        "**On when an AS is set.** BGP runs on this node while a local AS number is set. Clear the AS number to turn it off: the BGP section is removed from `frr.conf` and FRR keeps running. The **Router ID** can only be filled in while an AS number is set, and clearing the AS clears it too.",
        "**Announce only.** The node announces its anycast addresses and nothing else, and accepts no routes from its neighbors, so a peer cannot change this host's routing table.",
        "**Withdrawal.** An address exists in FRR's table only while Anyname holds it on `lo` (a DNS server answers, the gateway is not paused, Anyname is running), so the route is withdrawn when the node cannot answer. **BFD** is on for every neighbor; lower the timers on your router to shorten the time it takes to notice a dead node.",
        "An **IPv4** address is announced to IPv4 neighbors and an **IPv6** address to IPv6 neighbors; add a neighbor of each family to announce both.",
        "**Existing FRR setup.** The first time Anyname takes `frr.conf` over, the old file is kept as `frr.conf.pre-ddgw`. A change is applied with a reload, which needs the `frr-pythontools` package (the installer adds it); without it Anyname restarts FRR instead and the sessions drop briefly.",
      ]],
      ["h", "Neighbors"],
      ["ul", [
        "Press **+** above the table to add a row and fill it in: the neighbor is created once it has an address and an AS number. Click a row to highlight it and press **−** to remove it.",
        "Changes save when you leave a field. The password is an MD5 session password; it is kept in the config file and its history, readable by root only.",
      ]],
      ["h", "Fields"],
      ["fields", [
        ["Local AS number", "This node's AS number, for example `64512`. BGP runs on this node while it is set; clear it to turn BGP off."],
        ["Router ID", "An IPv4 address that identifies this router. Optional; empty lets FRR pick one. Needs a local AS number: the field is disabled until one is set."],
        ["Keepalive (seconds)", "How often this node sends a BGP keepalive. Default `3`. Must be shorter than the hold time."],
        ["AS Prepend", "When ticked, this node adds its local AS three more times to the AS path of every anycast address it announces (`set as-path prepend ASN ASN ASN` in the outbound route-map). A longer path makes routers prefer the nodes that do not have it ticked, so use it on the nodes that should be the backup. Per node, like the rest of this card; it applies at once."],
        ["Hold time (seconds)", "How long a silent peer is kept before the session is declared down. Default `9`, minimum `3`. The session uses the lower hold time of the two ends, so a peer with longer timers agrees down to this."],
        ["AS of (a neighbor's row)", "The neighbor's AS number. A neighbor is created once it has an address and an AS."],
        ["Description of (a neighbor's row)", "A note of up to 60 characters shown with the neighbor."],
        ["Password for (a neighbor's row)", "Optional MD5 session password; it must match the router's. Kept in the config file and its history, readable by root only."],
        ["New neighbor address", "The router's IPv4 or IPv6 address, for example `192.0.2.1` or `2001:db8::1`, in the empty row above the table."],
        ["New neighbor AS", "That router's AS number."],
        ["Multihop of (a neighbor's row)", "For an eBGP peer that is not on a directly connected subnet, for example an AWS VPC Route Server endpoint: the hop limit, usually `2`. Empty means directly connected. FRR then runs BFD to that peer in multihop mode as well, so the peer must be set up the same way (one side multihop and the other not leaves BFD down and the session resetting). Ignored for an iBGP neighbor."],
        ["New neighbor multihop", "Optional, 2-255. See *Multihop* in a neighbor's row."],
        ["New neighbor description", "Optional note."],
        ["New neighbor password", "Optional MD5 session password."],
      ]],
      ["cli", "ddgw --bgp\nddgw --asn 64512 --router-id 192.0.2.10   (--router-id needs an AS, set now or earlier)\nddgw --keepalive 3 --hold 9\nddgw --as-prepend on   (the local AS three more times on every announcement; off undoes it)\nddgw --bgp-neighbor-add 192.0.2.1 --remote-as 64500 --description core\nddgw --bgp-neighbor-add 10.0.1.5 --remote-as 64512 --multihop 2\nddgw --bgp-neighbor-del 192.0.2.1\nddgw --asn off   (also clears the router ID)\n(--password on the command line is visible to other users of the host; the page is safer)"],
    ],
  },
  anycastop: {
    title: "Anycast (operate)",
    body: [
      "Switch BGP on this node, or one of its neighbors, off and on without losing any setting. The settings themselves are under **Configure → Anycast**; what BGP is doing is under **Monitor → Anycast**. The page needs a local AS number to be set.",
      ["h", "The page"],
      ["ul", [
        "**BGP**: *Disable BGP* stops BGP on this node as if the AS were cleared (the BGP section leaves `frr.conf`, the sessions go down, nothing is announced) but keeps the AS, router ID, timers and neighbors. *Enable BGP* puts it back. The anycast addresses stay on `lo` and the gateways keep answering; only the announcing stops.",
        "**Neighbors**: right-click a neighbor and choose *Disable* to shut one session down (`neighbor … shutdown` in `frr.conf`) and nothing is announced to it; the neighbor stays configured and in the list. *Enable* (the same menu) brings it back. Neither works while BGP itself is disabled.",
        "Per node, like the rest of the BGP settings: another node is switched from the node picker at the top right.",
      ]],
      ["cli", "ddgw --bgp-disable\nddgw --bgp-enable\nddgw --bgp-neighbor-disable 192.0.2.1\nddgw --bgp-neighbor-enable 192.0.2.1"],
    ],
  },
  stats: {
    title: "Statistics",
    body: [
      "How many queries this node answered, how they ended and who asked for what. The numbers are counted by the DNS proxy itself, for every gateway on the node, and kept for **30 days**. They are held in memory and saved to the node's state directory every 5 minutes and when Anyname stops, so a restart or an update does not empty them (time Anyname was not running shows as a gap). The file holds client addresses and the names they asked for and is readable by root only; delete `stats.json.gz` in the state directory, with Anyname stopped, to forget it all.",
      ["h", "Reading the page"],
      ["ul", [
        "**Last Hour**, **Last Day**, **Last Week**, **Last Month** or **Custom** (a start and an end inside the last 30 days) set the range for everything on the page. The line chart uses one point per minute, 10 minutes, hour or 3 hours, depending on the range.",
        "**QPS** is queries per second in the last finished interval (a minute for the hour view, longer for the longer ranges); the small line gives the highest interval of the range, and the tooltip the average. Click it to draw queries per second in the chart instead of counts (with a kind such as **NX Domain** picked, it is that kind's rate); click it again, or any other tile, to go back. Right-click a name in **Top domains** for **Block**: it adds a NODATA row (any client, that exact name) at the top of the shared Policy-Based Resolution table and saves it, so the proxy answers that name itself from then on (for NXDOMAIN or REFUSED, edit the row on Configure ▸ DNS proxy ▸ Resolution). On a name that already has such a row the item reads **Unblock** and removes it. A rewritten name has a ✏️ after it and its item reads **Remove rewrite**. **Rewrite…** asks what the name should be answered with, and adds a row (any client, that exact name) with that as its Destination name: an address (`10.5.5.5`), records (`A 10.5.5.5; TTL 300`, `CNAME host.example.com`) or another name to ask the servers for instead. Right-click a client in **Top clients** for **Block** (a NODATA row for that client, any name: nothing that client asks is sent to the servers any more; a blocked client, and a domain that has a row of its own in the table (NODATA, NXDOMAIN, REFUSED or null for every client), have a 🚫 after the name, and its item reads **Unblock** and removes that row) and **Scan**: this node runs nmap against the client (the 100 commonest ports, service and OS detection, up to two minutes; it needs the `nmap` package, which the installer adds) and a short summary (whether it is up, the operating system, the MAC address and its maker, and the open ports with the service and version found on each) is shown in the client's tooltip when it is done. **Clear**, next to the range buttons, forgets the counts and top lists of this node, or of every node when the Node menu says Cluster. **Cache Hits** is the share of the lookups that could be cached which were answered from the answer cache in the chosen range (with how many that is); it says “off or unused” when the cache is switched off or nothing cacheable was asked. It is a separate figure, not a kind of answer, so it is not clickable and is not part of the other tiles. The tiles add up the range: **No Error** is an answer, **Server Failure** is SERVFAIL (including the ones Anyname makes itself when no upstream answers), **NX Domain** is a name that does not exist, **Refused** is REFUSED. **Updates** counts dynamic DNS updates Anyname forwarded to a zone's primary (they are part of the total, but are not counted again under No Error, Refused and so on; the small line says how many the primary did not accept, and the chart gets a line for them once there are any). **Clients** is the number of different addresses that asked.",
        "Click a name in the chart's legend to hide or show that line, and hover the chart for the values at one point.",
        "In a cluster, the **Node** menu's last entry, **Cluster**, shows every node's numbers added together: the lines, tiles and top lists are the sum over the nodes (a line above the tiles appears only when a node could not answer, and names it). A client that asked several nodes is counted once in each list's total but its rows are added; the **Clients** tile is the larger of the busiest node's count and the clients seen in the nodes' lists, so it can be lower than the true number.",
        "The two donuts split the range by record type and by transport (UDP or TCP). **Top clients** shows the reverse-DNS name under an address once it has been looked up (a moment after first showing). **Top domains** lists the names asked for most. **More** shows up to 100.",
        "Click a tile to see only that kind of answer: the chart then draws just that line, and the donuts and the top lists count only those queries (their titles say so, and the shares are of that kind). That is how you find out **which domains** get NX Domain, and **which clients** ask for them. Click **Total Queries** to get everything back. Updates works the same way: the chart shows just the updates, Top clients lists who sent them, Top domains lists the zones they were for, and the **Recent dynamic updates** card appears below. The Clients tile is not a filter.",
        "Click a **client** in Top clients to see which domains it asked for (Top domains then lists only those), or a **domain** in Top domains to see which clients asked for it. It combines with the tiles: NX Domain, then a client, shows the names that client fails on. **Show all** (or clicking the row again) clears it. For a very busy network the pairs are kept for the busiest few hundred per interval; the rest show as “(others)”.",
        "Hover a **client** to see every reverse-DNS name the daemon found for it (looked up in the background for every client in the list, first by asking the DNS servers this node forwards to, then with the node's own resolver; a name shows up a moment after the client first appears). Hover a **domain** to see its first IPv4 and IPv6 address (asked of the DNS servers this node forwards to) above its **whois** data: registrar, registrant (when not redacted), registered / updated / expires dates and name servers. The first hover asks the domain's registry from the picked node (TCP port 43), so **that domain name leaves your network** — only the name, nothing about who asked; answers are cached for a day. A name with no public suffix (printer.lan), an address, or a node that cannot reach port 43 shows why there is nothing. Below the names is the address's **whois** data from its regional registry (block, name, organization, country, origin AS), asked on the first hover from the picked node; private and reserved addresses have none.",
        "**Recent dynamic updates** (below the top lists; it appears when you click the **Updates** tile) shows the last 200 dynamic DNS updates this node handled, newest first, whatever range is picked: when, which client sent it, the zone, what it changed (for example “add host1.example.com A 192.0.2.7” or “delete old.example.com A”; at most 8 records, then “… and N more”), the primary server it went to (name and address) and how that answered, green for NOERROR and red for anything else. An update that could not be delivered says why instead of a primary (no SOA found for the zone, the primary did not answer, forwarding switched off in Settings). The list is saved with the statistics, so a restart keeps it.",
        "The page shows the node picked in the **Node** menu at the top; pick another member there to see its own statistics. Each node counts only the queries it answered itself.",
      ]],
      ["h", "Memory guard"],
      "Statistics, the host history and the answer cache live in memory. Every 30 seconds Anyname checks how much of the machine's memory (or of its container's limit) is in use; at **85%** or more it drops the oldest history — the oldest tenth of what the statistics and the host history cover, per round — and a tenth of the cached answers, measures again, and repeats (at most 5 rounds per check) until use is below the limit. Newer data always stays, and the newest hour is never dropped. When it has done so the footer of this page says when and what. `DDGW_MEMORY_LIMIT_PERCENT` in the daemon's environment changes the limit.",
      ["h", "Limits"],
      "Top lists are collected in 10-minute steps for the last day and in hourly steps for the 30 days, and keep the busiest 300 clients and 600 domains of each step; the rest are counted as “(others)” so a flood of random names cannot use up memory. A range longer than a day reads the hourly steps, so its top lists begin and end on a whole hour.",
      ["h", "Fields"],
      ["fields", [
        ["Time range", "The buttons **Last Hour**, **Last Day**, **Last Week**, **Last Month** and **Custom** set the range of everything on the page."],
        ["From", "With **Custom**: the start of the range, a date and time inside the last 30 days."],
        ["To", "With **Custom**: the end of the range. Press **Apply** to load it."],
      ]],
      ["cli", "ddgw --stats\nddgw --stats --all-nodes   (every cluster node's numbers added together)\nddgw --stats --stats-range 1d\nddgw --stats --stats-range 7d\nddgw --stats --stats-range 30d\nddgw --stats --stats-rcode nxdomain   (also servfail, refused, noerror, other, update: the lists count only that answer)\nddgw --stats --stats-client ADDR     (the domains that client asked for)\nddgw --stats --stats-domain NAME     (the clients that asked for that domain)\nddgw --whois NAME                    (the whois data the tooltip shows)\nddgw --dns-updates                   (the recent dynamic DNS updates, newest first)\n(the same totals, query types, transports and top 10 lists)"],
    ],
  },
  host: {
    title: "Host",
    body: [
      "How busy the machine Anyname runs on is, on the node picked in the **Node** menu: CPU, memory, disk and network. Anyname reads the numbers itself from the operating system every 10 seconds and keeps them for **30 days** (per-minute averages, like Statistics). They are saved to the state directory every 5 minutes and when Anyname stops, so a restart does not empty them. If memory use reaches 85% the **memory guard** drops the oldest history (see Statistics); the footer says so when it has.",
      ["h", "Reading the page"],
      ["ul", [
        "The **tiles** are the latest sample: CPU use (and the load average), memory in use (what is not available for programs, caches excluded), the fullest filesystem, how much of the time the busiest disk was busy, and network traffic in and out.",
        "The **charts** follow the range at the top (Last Hour to Last Month, or a custom start and end). Each point is an average; hover for the value and the peak (the busiest 10-second sample in that point). A gap means the daemon was not running.",
        "In a cluster, the **Node** menu's last entry, **Cluster**, shows the nodes as one machine: network rates, load averages, memory, swap and disk sizes and cores are **added**; CPU is the average over all the cores (a 12-core node counts three times a 4-core one), memory and each filesystem are per byte of the whole, disk busy is the mean, and a peak is the busiest node's (for the network, the sum of the nodes' peaks, an upper bound). The interface table lists every node's interfaces under its name. A line above the tiles appears only when a node could not answer, and names it.",
        "**Disk utilization** shows each filesystem's space in use (up to six, the largest first) together with how busy the disks were.",
        "**Network utilization** adds up the real interfaces. Loopback, ddgw's own virtual-MAC links (`ddgw1.1`), container and bridge plumbing (`veth*`, `docker*`, `br-*`, `virbr*`) and ports of a bridge or bond are left out so traffic is not counted twice. The interface table lists them all with the link speed the driver reports and each link's use (the busier direction as a share of that speed; “–” when the speed is unknown, as on most virtual machines).",
      ]],
      ["h", "Limits"],
      "Memory use is the machine's, not ddgw's. In a container or VM the numbers are what that system reports. Counters that go backwards (a reboot, an interface reset) give a gap instead of a spike.",
      ["h", "Fields"],
      ["fields", [
        ["Time range", "The buttons at the top (**Last Hour** to **Last Month**, or **Custom**) set the range of the charts."],
        ["From", "With **Custom**: the start of the range, inside the last 30 days."],
        ["To", "With **Custom**: the end of the range. Press **Apply** to load it."],
      ]],
      ["cli", "ddgw --host\nddgw --host --all-nodes   (the cluster as one machine)\nddgw --host --host-range 1d\nddgw --host --host-range 7d\nddgw --host --host-range 30d\n(now, average and peak of CPU, memory, disk I/O and network, plus the filesystems and interfaces)"],
    ],
  },
  capture: {
    title: "Capture",
    body: [
      "A packet capture, like `tcpdump`, on one node or on every node of the cluster at once. It only listens: nothing is sent, nothing is changed. It needs the daemon's own privileges and it is off until you press Start.",
      ["h", "One node"],
      ["ul", [
        "The capture runs on the node chosen in the **Node** menu. Pick an **interface** (a gateway's interface is marked, and the virtual-MAC interfaces `ddgwN.M` are there too), optionally a **filter**, and press **Start**.",
        "The newest packets are listed live, one line each: TCP flags, DNS names and answers (`DNS A? example.com`, `DNS NXDOMAIN 0 ans`), ARP and IPv6 neighbor discovery with the Ethernet addresses they were sent from and to (`ARP, 10.20.0.205 is-at 00:1a:7c:01:02:00 (eth 02:… > …)`), which shows at once whether the virtual MAC a client is told about is the one that answers.",
        "The buffer holds the newest 5000 packets, or 32 MB. **Download .tgz** saves it as an archive with one `.pcap` in it, for Wireshark or tcpdump (through another node, the newest part that fits about 5 MB). **Clear** empties the list, **Stop** ends the capture (what was captured stays until you start again). A node has one capture: starting another replaces it.",
      ]],
      ["h", "Every node"],
      "Choose **Cluster** in the Node menu. **Capture on all nodes** runs the same capture on every node at the same moment for 5, 10, 30 or 60 seconds, then **Download .tgz** gives one `.pcap` per node (this node's is marked `-this-node`), a `summary.txt`, and an `errors.txt` naming any node that could not capture and why. Each node keeps its newest packets (about 4 MB). This does not touch what anyone has on a node's own Capture page. It is the way to see whether what one node sent is what another received.",
      ["h", "Filter"],
      "The filter is a small version of the tcpdump language, applied on the node before a packet is kept: `host 10.0.0.5`, `src host`, `dst host`, `net 10.0.0.0/24`, `port 53`, `src port`, `dst port`, `portrange 50-60`, `tcp`, `udp`, `icmp`, `icmp6`, `arp`, `ip`, `ip6`, `dns` (port 53), `ether host 00:1a:7c:01:02:00` (also `src`, `dst`), joined with `and`, `or`, `not` and brackets. A protocol before host, net or port narrows it (`tcp port 53`). A mistake is reported when you press Start. Names are not looked up: give addresses. An empty filter keeps everything, which on a busy DNS server fills the buffer in moments, so filter.",
      ["h", "Fields"],
      ["fields", [
        ["Interface", "The interface to listen on. In Cluster mode every node must have an interface of that name (the list is this node's); a node without it is reported in the result."],
        ["Filter", "Optional, up to 300 characters, as above. Press Enter to start."],
        ["How long", "Cluster mode only: 5, 10 (default), 30 or 60 seconds."],
      ]],
      ["cli", "ddgw --capture-interfaces\nddgw --capture eth0 --capture-seconds 10 --capture-filter \"host 10.20.0.205 and port 53\"\nddgw --capture eth0 --capture-file /tmp/eth0.pcap\nddgw --capture eth0 --capture-seconds 30 --all-nodes --capture-file /tmp/cluster.tgz\n(without --capture-file the packets are printed, the first 500; with --all-nodes a file is needed)"],
    ],
  },
  log: {
    title: "Log",
    body: [
      "The daemon's log on the node this page is acting on (use the **Node** menu to pick another member). It is the same text that goes to the system journal, kept as well in a file in the state directory (`ddgw.log`, rotated at 2 MB with the two previous files kept), so it survives a restart.",
      ["h", "Finding things"],
      ["ul", [
        "**Filter** takes words; a line must contain every one of them (any case), for example `10.0.0.5 DOWN` or `domain google.com`.",
        "**Level** keeps lines at that level and above. Debug lines exist only while the daemon's log level is *debug* (Configure ▸ General).",
        "**Time range** and **lines** bound the answer; the status line under the list says when older lines were cut.",
        "**Live** refreshes every few seconds and follows the newest line while you are at the bottom; scroll up to read and it stops following. **Download** saves what is shown as a text file.",
      ]],
      ["h", "tshoot"],
      "**tshoot** downloads one .tgz with everything that helps to find out why something does not work, from **every node** of the cluster (the node you are signed in to asks the others, whichever node the Node menu has picked): each node's log (the newest 20000 lines), configuration and its saved versions, cluster view, gateway, DNS-pool, BGP, anycast, virtual-MAC-test and update state, host numbers for the last hour, the addresses, links, routes (every table), rules, neighbors, ARP, listening sockets, the sysctl settings that matter to ARP and routing, the firewall rules, FRR's BGP and BFD output and configuration, service status, the system journal of Anyname, the kernel log tail and the system's version and load. It always includes 8 seconds of ARP and neighbor-discovery traffic on each gateway interface and a dump of every goroutine of the daemon (what it is busy with, for a node that is up but stuck). Passwords, the gateway key, tokens, join codes and private keys are removed before anything is written, command lines of other programs are not included, and each node's README.txt lists the files and says what could not be collected. A node that cannot be reached has a note instead of a folder. Nothing is changed on any node.",
      ["h", "What is logged"],
      "Server up and down changes, domains that start or stop answering on a server (so a single failing domain shows even while the server stays up), gateway start-up and hand-over, a node's CPU, memory or fullest disk going over 85% (a warning, naming what is over; this node and every cluster member) and the line when it is back at 85% or below, configuration changes (each one says what was enabled, disabled, paused or resumed), updates (including auto-update turned on or off), BGP and web sign-in events.",
      ["h", "Fields"],
      ["fields", [
        ["Filter text", "Words, separated by spaces. A line is shown only if it contains every one, in any case. Applied as you type."],
        ["Level", "All levels, Info and above, Warnings and errors, or Errors only. Default all."],
        ["Time range", "How far back to read: 15 minutes, an hour (default), 6 hours, 24 hours, 7 days or all of it."],
        ["Lines", "The most lines shown: 200, 1000 (default) or 5000, newest kept."],
        ["Live", "Ticked (the default): the list refreshes every few seconds and follows the newest line while you are at the bottom."],
      ]],
      ["cli", "ddgw --tshoot --all-nodes   (the tshoot bundle of every node, written to ddgw-tshoot-HOST-TIME.tgz; without --all-nodes just this node; --tshoot-file F.tgz names the file; the ARP / neighbor-discovery capture is always taken)\nkill -USR1 $(pidof ddgw)   (writes every goroutine's stack to the journal: journalctl -u ddgw; for a daemon that is up but not answering)\nddgw --log\nddgw --log --log-min warn --log-since 6h\nddgw --log --log-grep \"server 192.0.2.53\" --log-lines 200\n(without --log-lines the whole matching log is printed; redirect it to a file to keep it)"],
    ],
  },
  node: {
    title: "Node",
    body: [
      "What this node does and the machine it runs on. The **Node** menu in the top right picks another member to act on.",
      ["h", "Gateway controller"],
      "**Make this node the gateway controller** asks the current controller (AGC) to hand the shared address to this node. This node takes the role first and then the old controller steps down without taking its virtual MAC or its DNS down, so clients should lose nothing; a client that cached the old controller's MAC is still answered while the new one takes that MAC over. To prefer a node permanently, raise its priority (and turn on preemption) in Settings instead.",
      ["h", "Maintenance"],
      "**Pause this node** pauses every gateway on it at once (the same as pausing each gateway on the Topology page, but it also covers gateways added later). The node resigns, stops answering DNS and stops probing; the other nodes carry the traffic. Nothing is shut down, and the setting is kept across restarts of Anyname and of the host. **Resume this node** brings its gateways back once their DNS servers answer. It is useful for sending all traffic to one node, for example to benchmark it: pause the others instead of shutting them down. A gateway you paused yourself stays paused after the node is resumed.",
      ["h", "Host"],
      "It is the machine that reboots, not just ddgw.",
      ["h", "Restart or shut down"],
      ["ul", [
        "Choose **Restart** or **Shut down**, then **Now**, **In** a number of minutes (up to 7 days) or **At** a time of day (24-hour, the host's clock), and press **Execute**. You are asked to confirm.",
        "A shut-down host stays off until it is powered on again, from its console or out-of-band.",
        "A scheduled action is kept by the operating system, so it survives a restart of ddgw. It shows here as a notice with **Cancel it**.",
      ]],
      ["h", "Protecting the gateway"],
      "An action started **now** is refused when this node is the only member serving one of its gateways, so a reboot never leaves clients without an answer; you are asked whether to go ahead anyway. The check is made when you press Execute, not at the scheduled time, so for a later time make sure another member will be serving by then. When a node stops, a controller announces that it is leaving, so another member takes over at once.",
      ["h", "Host fields"],
      ["fields", [
        ["Action", "**Restart host** (the default) or **Shut down host**. It acts on the whole machine."],
        ["When", "**Now** (default), **In** a number of minutes, or **At** a time of day. Clicking into the minutes or time box selects its option."],
        ["Minutes", "With **In**: 1–10080 minutes (up to 7 days), default 5."],
        ["Time of day", "With **At**: a 24-hour time on the host's clock; if it has passed today it means tomorrow."],
      ]],
      ["cli", "ddgw --assert-agc\nddgw --node-pause\nddgw --node-resume\nddgw --node-status\nddgw --power restart|shutdown\nddgw --power restart --in 10\nddgw --power shutdown --at 02:30\nddgw --power status\nddgw --power cancel\n(--yes skips the question and goes ahead even if a gateway would be left unserved)"],
    ],
  },
  users: {
    title: "Users",
    body: [
      "The accounts that may sign in to this web GUI: the members of the GUI group (`ddgw` unless `web.group` says otherwise). They are ordinary operating-system accounts, so a password set here is the one PAM checks. In a cluster every change here is made on **every node** (the password hash is sent, not the password); if a node could not be reached the message says which, and the change can be repeated when it is back.",
      ["h", "What it does"],
      ["ul", [
        "The accounts are listed on the left (with a filter box); pick one to work on it on the right. **+ New** opens the form for a new account.",
        "**Add user** creates an account with no shell and no home directory, in the GUI group, so it can sign in here and do nothing else on the machine.",
        "Pick an account, then type a **New password** and/or change **Expires**, and press **Save** (Enter in the password field does the same). A blank date means the account never expires; from the date on the operating system refuses the account.",
        "**Add an existing account…** puts an account that is already on the machine into the GUI group so it can sign in here with the password it already has (nothing about the account is changed). The Name box suggests the ordinary accounts that are not in the group yet; type any other account name to add that one. On the other nodes the account is added to the group where it exists and created with the same password where it does not.",
        "**Disable** takes the account out of the GUI group and keeps the account (it just cannot sign in here any more). It works for any listed account except yourself and the last one; an account that is in the group only because it is its primary group is refused, with the reason.",
        "**Delete** removes the account. You cannot delete yourself or the last account that can sign in.",
        "Only accounts in the GUI group are listed, and `root` never is. *Add user* never changes an account that already exists on a machine; use *Add an existing account…* for that.",
        "A node that was down misses a change. Setting the password sends the whole account again (and creates it where it is missing), so setting the password again brings it back in line; `ddgw --user-del NAME` can repeat a delete.",
        "A node that **joins** a cluster gets its existing accounts copied (with their passwords and expiry); an account that already exists on the new node is left as it is.",
        "Every member can manage every other member, which is the same power they already have over the daemon. Changes are logged with who made them.",
      ]],
      ["h", "Fields"],
      ["fields", [
        ["Name", "Lower-case letters, digits, `_` and `-`, up to 32 characters, starting with a letter or `_`. In *Add existing user*, the name of an account that is already on the machine."],
        ["Password", "The new account's password. It is passed to the system on standard input, never on a command line."],
        ["Expires", "Optional date after which the account cannot sign in. Empty means never."],
      ]],
      ["cli", "ddgw --users\nddgw --user-add NAME [--expires YYYY-MM-DD]\nddgw --user-passwd NAME\nddgw --user-expiry NAME --expires YYYY-MM-DD|never\nddgw --user-del NAME\nddgw --user-grant NAME\nddgw --user-revoke NAME"],
    ],
  },
  _default: { title: "Help", body: ["No help has been written for this page yet."] },
};
