#!/usr/bin/env python3
"""Regenerates the icon block of source/web/ui.css.

The UI's icons are drawn here, by hand, on a 16x16 grid. Each one becomes a CSS
rule `.bi-NAME { --i: url("data:image/svg+xml,...") }`; ui.css paints them as a
mask over `currentColor`, so an icon takes the text colour of whatever it sits
in and no font or image file is shipped.

Usage:  python3 contrib/icons/gen.py            (rewrites the block in place)
        python3 contrib/icons/gen.py --sheet    (prints a standalone HTML contact sheet)

Only the standard library is used, like the rest of the project.
"""
import re
import sys
from pathlib import Path
from urllib.parse import quote

CSS = Path(__file__).resolve().parents[2] / "source" / "web" / "ui.css"
BEGIN, END = "/* BEGIN ICONS (generated by contrib/icons/gen.py) */", "/* END ICONS */"

# Painting styles. Only the alpha channel matters (the SVG is used as a mask).
S = "fill='none' stroke='black' stroke-width='1.4' stroke-linecap='round' stroke-linejoin='round'"
F = "fill='black'"


def stroke(*d):
    return "<g %s>%s</g>" % (S, "".join("<path d='%s'/>" % p for p in d))


def fill(*d, rule=None):
    extra = " fill-rule='evenodd'" if rule else ""
    return "".join("<path %s%s d='%s'/>" % (F, extra, p) for p in d)


def cutout(shape, *marks, sw=1.5):
    """A filled shape with strokes punched out of it (transparent in the mask)."""
    cut = "".join("<path d='%s'/>" % m for m in marks)
    return (
        "<mask id='m'><rect width='16' height='16' fill='white'/>"
        "<g fill='none' stroke='black' stroke-width='%s' stroke-linecap='round' stroke-linejoin='round'>%s</g></mask>"
        "<g mask='url(#m)' %s>%s</g>" % (sw, cut, F, shape)
    )


CIRCLE = "<circle cx='8' cy='8' r='7'/>"
CHECK = "M4.9 8.3l2 2 4.2-4.4"
CROSS = "M5.6 5.6l4.8 4.8M10.4 5.6l-4.8 4.8"

ICONS = {
    "arrow-clockwise": stroke("M13 8a5 5 0 1 1-1.46-3.54") + fill("M13.1 6L12.74 2.84 9.92 5.66z"),
    "arrow-left": stroke("M13.5 8h-11", "M6.6 4L2.6 8l4 4"),
    "bar-chart": fill("M2.5 8.5h3v5.5h-3z", "M6.5 2.5h3V14h-3z", "M10.5 6h3v8h-3z"),
    "box-arrow-in-right": stroke("M1.8 8h7.2", "M6.4 5.3L9.1 8l-2.7 2.7", "M9 2.5h3.5a1 1 0 0 1 1 1v9a1 1 0 0 1-1 1H9"),
    "box-arrow-right": stroke("M9 2.5H3.5a1 1 0 0 0-1 1v9a1 1 0 0 0 1 1H9", "M6.5 8h7.2", "M11.1 5.3L13.8 8l-2.7 2.7"),
    "calendar-check": stroke("M3.5 3h9A1.5 1.5 0 0 1 14 4.5v8a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 12.5v-8A1.5 1.5 0 0 1 3.5 3z",
                              "M2 6.5h12", "M5 1.5v3M11 1.5v3", "M5.9 10.3l1.6 1.6 3-3.2"),
    "check-circle-fill": cutout(CIRCLE, CHECK),
    "check2": stroke("M3 8.5l3.3 3.3L13 4.8"),
    "circle-half": stroke("M8 1.8a6.2 6.2 0 1 0 0 12.4a6.2 6.2 0 0 0 0-12.4z") + fill("M8 1.8a6.2 6.2 0 0 0 0 12.4z"),
    "clipboard": stroke("M4.5 2.8H4a1 1 0 0 0-1 1V14a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V3.8a1 1 0 0 0-1-1h-.5",
                         "M6 1.3h4a.8.8 0 0 1 .8.8v1.4a.8.8 0 0 1-.8.8H6a.8.8 0 0 1-.8-.8V2.1A.8.8 0 0 1 6 1.3z"),
    "clipboard-check": stroke("M4.5 2.8H4a1 1 0 0 0-1 1V14a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V3.8a1 1 0 0 0-1-1h-.5",
                               "M6 1.3h4a.8.8 0 0 1 .8.8v1.4a.8.8 0 0 1-.8.8H6a.8.8 0 0 1-.8-.8V2.1A.8.8 0 0 1 6 1.3z",
                               "M5.7 9.4l1.7 1.7 3-3.3"),
    "clock": stroke("M8 1.8a6.2 6.2 0 1 0 0 12.4A6.2 6.2 0 0 0 8 1.8z", "M8 4.6V8l2.4 1.5"),
    "copy": stroke("M5.5 5.5h7a1.2 1.2 0 0 1 1.2 1.2v6.6a1.2 1.2 0 0 1-1.2 1.2h-7a1.2 1.2 0 0 1-1.2-1.2V6.7a1.2 1.2 0 0 1 1.2-1.2z",
                   "M11.4 3.2V2.7a1.2 1.2 0 0 0-1.2-1.2H3.4a1.2 1.2 0 0 0-1.2 1.2v6.6a1.2 1.2 0 0 0 1.2 1.2h.9"),
    "download": stroke("M8 2v8", "M4.8 7.2L8 10.4l3.2-3.2", "M2.5 10.5V13a.8.8 0 0 0 .8.8h9.4a.8.8 0 0 0 .8-.8v-2.5"),
    "file-earmark-text": stroke("M4 1.6h5.4l3.6 3.6v8.2a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2.6a1 1 0 0 1 1-1z",
                                 "M9.2 1.8v3.6h3.6", "M5.4 8.2h5.2M5.4 10.4h5.2M5.4 12.4h3"),
    "file-text": stroke("M4 1.6h8a1 1 0 0 1 1 1v10.8a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2.6a1 1 0 0 1 1-1z",
                         "M5.4 5.2h5.2M5.4 8h5.2M5.4 10.8h3"),
    "hdd-network": stroke("M2.8 2.2h10.4a1 1 0 0 1 1 1v3.6a1 1 0 0 1-1 1H2.8a1 1 0 0 1-1-1V3.2a1 1 0 0 1 1-1z",
                           "M8 7.8v2.6", "M3.4 10.4h9.2v1.4") +
                   "<circle cx='4.4' cy='5' r='.85' fill='black'/>" +
                   fill("M2 11.6h2.8v2.6H2z", "M6.6 11.6h2.8v2.6H6.6z", "M11.2 11.6H14v2.6h-2.8z"),
    "list-check": stroke("M1.8 3.4l1 1 1.7-1.9", "M1.8 8.2l1 1 1.7-1.9", "M1.8 13l1 1 1.7-1.9",
                          "M7.2 3.6h7M7.2 8.4h7M7.2 13.2h7"),
    "lock": stroke("M4.5 7.2h7a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1h-7a1 1 0 0 1-1-1v-5a1 1 0 0 1 1-1z", "M5.5 7.2V5a2.5 2.5 0 0 1 5 0v2.2"),
    "moon-stars-fill": fill("M6.2 1.4a6.6 6.6 0 1 0 8.4 8.4 5.6 5.6 0 0 1-8.4-8.4z",
                             "M11.6 1.6l.5 1.4 1.4.5-1.4.5-.5 1.4-.5-1.4-1.4-.5 1.4-.5z"),
    "pause-circle": stroke("M8 1.8a6.2 6.2 0 1 0 0 12.4A6.2 6.2 0 0 0 8 1.8z", "M6.5 5.9v4.2M9.5 5.9v4.2"),
    "pie-chart": stroke("M8 1.8a6.2 6.2 0 1 0 0 12.4a6.2 6.2 0 0 0 0-12.4z") + fill("M8.9 7.1V2.1A5.9 5.9 0 0 1 13.9 7.1z"),
    "pencil": stroke("M10.6 2.4a1.2 1.2 0 0 1 1.7 0l1.3 1.3a1.2 1.2 0 0 1 0 1.7L5.7 13.3l-3.4.9.9-3.4z", "M9.4 3.6l3 3"),
    "person": stroke("M8 8.2a2.8 2.8 0 1 0 0-5.6 2.8 2.8 0 0 0 0 5.6z", "M2.8 14c0-2.8 2.2-4.6 5.2-4.6s5.2 1.8 5.2 4.6"),
    "play-circle-fill": cutout(CIRCLE, "M6.6 5.4l3.6 2.6-3.6 2.6z", sw=1.2),
    "play-fill": fill("M4.4 2.9a.6.6 0 0 1 .9-.5l7.6 4.8a.6.6 0 0 1 0 1L5.3 13a.6.6 0 0 1-.9-.5z"),
    "plus-lg": stroke("M8 2.4v11.2M2.4 8h11.2"),
    "sliders": stroke("M2 4h4.2", "M10.8 4H14", "M2 8h1.7", "M8.3 8H14", "M2 12h5.2", "M11.8 12H14",
                      "M8.5 4m-2.3 0a2.3 2.3 0 1 0 4.6 0a2.3 2.3 0 1 0-4.6 0",
                      "M6 8m-2.3 0a2.3 2.3 0 1 0 4.6 0a2.3 2.3 0 1 0-4.6 0",
                      "M9.5 12m-2.3 0a2.3 2.3 0 1 0 4.6 0a2.3 2.3 0 1 0-4.6 0"),
    "shuffle": stroke("M1.8 4.6h2.4c3.4 0 4.2 6.8 7.6 6.8h2.4", "M1.8 11.4h2.4c1.5 0 2.4-1.2 3.2-2.5", "M8.8 7.1c.8-1.4 1.7-2.5 3-2.5h2.4",
                       "M12.4 2.6l1.8 2-1.8 2", "M12.4 9.4l1.8 2-1.8 2"),
    "speedometer2": stroke("M2 12.4a6.5 6.5 0 1 1 12 0c-1.5.9-3.6 1.3-6 1.3s-4.5-.4-6-1.3z", "M8 10.6l2.6-3.9",
                            "M8 3.8v1.2M4.4 5.4l.9.9M11.6 5.4l-.9.9M3 9h1.2M11.8 9H13") +
                    "<circle cx='8' cy='10.6' r='1.1' fill='black'/>",
    "stop-fill": fill("M4.5 3.5h7a1 1 0 0 1 1 1v7a1 1 0 0 1-1 1h-7a1 1 0 0 1-1-1v-7a1 1 0 0 1 1-1z"),
    "sun-fill": "<circle cx='8' cy='8' r='3' fill='black'/>" +
                stroke("M8 1.4v1.7M8 12.9v1.7M1.4 8h1.7M12.9 8h1.7M3.3 3.3l1.2 1.2M11.5 11.5l1.2 1.2M12.7 3.3l-1.2 1.2M4.5 11.5l-1.2 1.2"),
    "terminal": stroke("M3 2.6h10a1.5 1.5 0 0 1 1.5 1.5v7.8A1.5 1.5 0 0 1 13 13.4H3a1.5 1.5 0 0 1-1.5-1.5V4.1A1.5 1.5 0 0 1 3 2.6z",
                        "M4.6 6l2.3 2-2.3 2", "M8.4 10.3h3"),
    "terminal-fill": cutout("<rect x='1' y='2' width='14' height='12' rx='2'/>", "M4.4 5.9l2.3 2.1-2.3 2.1", "M8.3 10.3h3.2"),
    "trash": stroke("M2.5 4h11", "M6 4V2.4h4V4", "M3.8 4l.7 9.2a1 1 0 0 0 1 .9h5a1 1 0 0 0 1-.9l.7-9.2", "M6.6 6.6v5M9.4 6.6v5"),
    "upload": stroke("M8 10.2V2.4", "M4.9 5.3L8 2.2l3.1 3.1", "M2.4 10v2.6a1.2 1.2 0 0 0 1.2 1.2h8.8a1.2 1.2 0 0 0 1.2-1.2V10"),
    "x-circle-fill": cutout(CIRCLE, CROSS),
    "x-lg": stroke("M3 3l10 10M13 3L3 13"),
}


def uri(body):
    svg = "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'>%s</svg>" % body
    return "data:image/svg+xml," + quote(svg, safe="/:=' ,().-_~")


def block():
    out = [BEGIN]
    for name in sorted(ICONS):
        out.append('.bi-%s{--i:url("%s")}' % (name, uri(ICONS[name])))
    out.append(END)
    return "\n".join(out)


def sheet():
    cells = "".join(
        "<div style='display:inline-block;width:110px;text-align:center;margin:6px;font:11px sans-serif'>"
        "<i class='bi bi-%s' style='font-size:40px'></i><br>%s</div>" % (n, n) for n in sorted(ICONS))
    return "<!doctype html><link rel=stylesheet href=/ui.css><body style='background:var(--body-bg);color:var(--body-color)'>%s" % cells


if __name__ == "__main__":
    if "--sheet" in sys.argv:
        print(sheet())
    else:
        css = CSS.read_text()
        pat = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
        if not pat.search(css):
            sys.exit("markers not found in %s" % CSS)
        CSS.write_text(pat.sub(lambda m: block(), css))
        print("wrote %d icons into %s" % (len(ICONS), CSS))
